//! ALPS UI — entry point.
//!
//! See `SPEC.md` and `DESIGN.md` in the repo root for the full design.
//! This is the first-cut scaffold (US-001 → US-006): a Dioxus 0.7
//! fullstack app that ships web / desktop / mobile from a single `rsx!{}`
//! tree, backed by read-side server functions (US-006) over the `alps-core`
//! domain types re-exported from `crate::domain`.
//!
//! ## Module map (as of US-006)
//!
//! - `domain` — UI-side mirror of `alps_core::summary` / `receipt` / `domain`
//!   types. Only `TaskId` is re-declared (a thin newtype used as a typed
//!   router path segment); everything else is `pub use`-re-exported.
//! - `routes` — the `Route` enum (the typed router). 7 variants per SPEC §5.
//! - `layouts` — components that wrap one or more `Route` variants. Right
//!   now only `NavBar` (the responsive top-bar + hamburger + Outlet).
//! - `pages` — one placeholder component per `Route` variant. US-005 fills
//!   in `Dashboard`; US-007+ fills in the rest as server functions land.
//! - `fixtures` — the hardcoded `TaskSummary` fixture list rendered by the
//!   Dashboard (US-005). Eight rows, one per normal `TaskState` variant.
//! - `components` — the named presentation fragments from DESIGN.md §4:
//!   `StatusPill`, `StoryCard`, `FindingCard`, `AssertionCard`,
//!   `ReceiptCard`, `ResponsiveGrid`. US-005 wires them into the
//!   Dashboard; US-007+ wires them into TaskDetail once server functions
//!   arrive.
//! - `api` — `#[server]`-decorated functions behind `#[cfg(feature = "server")]`
//!   per SPEC §7.2 / US-006. Currently `tasks_list`, `task_get`, and the
//!   deferred-stub `task_run`. The module is invisible in the `web`-only
//!   default build, so no `Command::new` strings reach the wasm.
//!
//! ## Why `dioxus::router` (not `dioxus_router`)
//!
//! `dioxus-router` is a transitive dependency of `dioxus`. The dioxus crate
//! re-exports it as `dioxus::router` (see `dioxus-0.7.10/src/lib.rs`), so we
//! use that alias — adding a direct `dioxus-router = "0.7"` line to
//! `Cargo.toml` would be redundant. The `Routable` derive macro is also
//! re-exported through `dioxus::prelude::*`.

use dioxus::prelude::*;
use dioxus::router::components::Router;

mod api;
mod components;
mod domain;
mod fixtures;
mod layouts;
mod pages;
mod routes;

use routes::Route;

fn main() {
    dioxus::launch(App);
}

#[component]
fn App() -> Element {
    rsx! {
        // Router takes no required props — the `Route` type parameter carries
        // the typed router. The router parses the current URL through
        // `Route::from_str`, matches it against the `SITE_MAP` generated by
        // `#[derive(Routable)]`, and renders the matched route's component
        // inside the matched layout's `<Outlet::<Route>>`. On parse failure
        // the router returns a "Route did not match" placeholder.
        Router::<Route> {}
    }
}
